#!/usr/bin/env bash

# Setup files to be sourced
load_dotfiles() {
    declare -a files=(
        $HOME/.dotfiles/shell/paths # Path modifications
        $HOME/.dotfiles/shell/options # Options
        $HOME/.dotfiles/shell/exports # Exports
        $HOME/.dotfiles/shell/aliases # Aliases
        $HOME/.dotfiles/shell/bash_prompt # Custom bash prompt
        $(brew --prefix)/share/bash-completion/bash_completion # Bash completion
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles

# Enable tab completion for `g` by marking it as an alias for `git`
if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
	complete -o default -o nospace -F _git g;
fi;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults;

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall;

# Load nvm at login
export NVM_DIR="$HOME/.nvm"
source "$(brew --prefix nvm)/nvm.sh"

# Add ssh-keys to ssh-agent
