#!/bin/bash

run_help() {

cat <<EOT
dotfiles

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Copyright (c) Nicolas Gallagher
Licensed under the MIT license.
EOT

}