#!/usr/bin/env bash


run_brew() {
	
}
### Install Brews

# Install command-line tools using Homebrew.

# Check if Homebrew is already installed
if ! type_exists 'brew'; then
	e_header "Homebrew is not installed, getting latest version."
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	[[ $? ]] && e_success "Homebrew installed"
else
	e_header "Updating Homebrew ..."
	brew update
	[[ $? ]] && e_success "Done"
fi;

# Tap casks
brew tap homebrew/versions
brew tap homebrew/dupes

# Upgrade any already-installed formulae.
e_header "Updating any existing Homebrew formulae ..."
brew upgrade
[[ $? ]] && e_success "Done"

apps=(
	coreutils
	python3
	bash
	bash-completion2
	git --with-brewed-curl --with-brewed-openssl
	curl --with-openssl --with-libssh2
	moreutils
	composer
	htop
	gnu-sed --with-default-names
	grep --with-default-names
	findutils --with-default-names
	dockutil
	wget --with-iri
	wifi-password
	vim --with-override-system-vi
	lastpass-cli
	homebrew/dupes/openssh
	homebrew/dupes/screen
#	homebrew/php/php56 --with-mssql --with-homebrew-curl --with-homebrew-libxml2 --with-pear
)
#brew install "${apps[@]}"
unset apps

ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# Switch to using brew-installed bash as default shell
if ! fgrep -q '/usr/local/bin/bash' /etc/shells; then
  echo '/usr/local/bin/bash' | sudo tee -a /etc/shells;
  chsh -s /usr/local/bin/bash;
fi;