#!/usr/bin/env bash

run_cask() {
	if type_exists 'brew'; then
	    e_header "Updating Homebrew Cask ..."
        [[ $? ]] && e_success "Done"
		
		# Tapping
		brew tap Caskroom/versions

        e_header "Checking status of desired Homebrew casks ..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
			'iterm'
			'bettertouchtool'
			'dash'
			'dropbox'
			'flux'
			'pycharm-ce'
			'google-chrome'
			'google-chrome-canary'
			'google-drive'
			'sublime-text'
			'vlc'
    	)

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            fi
        done

        if [[ "$missing_formulae" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            e_header "Installing missing Homebrew formulae ..."
            # Install all missing formulae
            brew install $list_formulae

            [[ $? ]] && e_success "Done"
        fi

        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}